### ISSUE TITLE
[제안] 테스트케이스 메소드명 역할

### ISSUE THREAD

**Issue by siyoungoh** [hanghae99-mucosa/server#10]
https://github.com/hanghae99-mucosa/server/blob/2086787872fd06b6a968a6739cddf0f9f67e9028/src/test/java/com/hanghae99/mocosa/integration/ProductIntegrationTest.java#L81

서비스가 커지고 계속 유지되다보면 유지보수 측면에서 가독성이 훨씬 더 중요해져요. 가독성과 버그 발생이 연관이 있습니다. 
지금처럼 case넘버링 으로 관리하다보면 문서와 코드 모두를 관리해야해서 관리 리소스가 더 들어갈 수도 있어요. 

아래처럼 테스트케이스 메소드를 작성할 수도 있습니다. 
처음 프로덕트를 파악할 때 테스트케이스명으로 프로덕트의 주요 기능을 파악하기도 합니다. 

`public void Todo삭제요청하면_should_delete가_true인_store를_호출하는지_확인()`

**Comment by jjucc99** [comment]
오호 Yes, ma'am

**Comment by Backseungchan** [comment]
확인해서 수정하였습니다.
