### ISSUE TITLE
주석 사용

### ISSUE THREAD

**Issue by siyoungoh** [hanghae99-mucosa/server#9]
https://github.com/hanghae99-mucosa/server/blob/2086787872fd06b6a968a6739cddf0f9f67e9028/src/main/java/com/hanghae99/mocosa/config/exception/code/ErrorCode.java#L12 

이제 조금씩 주석을 코드 자체의 가독성으로 대체하는 걸 시도해보세요. 어떤 로직인지 주석이 아니라 코드만으로 읽히도록.

**Comment by dongil618** [comment]
네! 피드백 감사합니다. 최대한 코드로만 읽히도록 가독성 높은 코드 작성하도록 하겠습니다. 해당 주석들은 팀원들과 논의 후에 제거해 나가도록 하겠습니다.
